version: '3.4'

services:
  mongo:
    image: mongo

  blog:
    build:
      context: .
      target: blog
    environment:
      - MONGO_URI=mongodb://mongo
      - USER=${USERNAME:-admin}
      - PASS=${PASSWORD:-admin}
      - ADDR=:80
